### ISSUE TITLE
Double Ayase

### ISSUE THREAD

**Issue by rougeBlatant** [acidpoison/Jade#11]
After choosing "No" (Or the refusal option) at the beginning while in the forest, and then choosing 'Why not' Ayase Doubles, this happens after Jade fades out to lave. Ayase then doubles and then both of them leave.
![x2al](https://cloud.githubusercontent.com/assets/12416255/7594827/356ed602-f8db-11e4-9d4c-3f4adf1e6ca5.png)

**Comment by acidpoison** [comment]
Duplicate issue of #7. I'll re-open it if it's not fixed. Please make sure you have the most recent version.

**Comment by Aami** [comment]
Did you try the new version I sent to you? Because, it works fine for me.
