### ISSUE TITLE
Background gone

### ISSUE THREAD

**Issue by rougeBlatant** [acidpoison/Jade#12]
After choosing 'No' and 'Why not' previously in the forest, all backgrounds have disappeared. After moving through several missing frames I recognise the is not a one time occurrence. This occurred after Ayase doubling (look at my former post for more information on that.)
![bggone](https://cloud.githubusercontent.com/assets/12416255/7595327/3e63e010-f8de-11e4-9ca1-9815c5ee8c86.png)

**Comment by acidpoison** [comment]
See #11.
