### ISSUE TITLE
Unable to skip splash screen

### ISSUE THREAD

**Issue by acidpoison** [acidpoison/Jade#2]
People coming back to continue a game might be annoyed that there is no way to skip the splash screen.

**Comment by Aami** [comment]
I added a "Click to skip" button to the WARNING part.

**Comment by Aami** [comment]
Hah, no, I just made it last shorter.

**Comment by acidpoison** [comment]
I'll check it out in the new version.

**Comment by acidpoison** [comment]
It's still kinda annoying, but I can deal with it.
