### ISSUE TITLE
Return to title screen from the settings window replays splash screens

### ISSUE THREAD

**Issue by acidpoison** [acidpoison/Jade#4]
Clicking the Return to Title Screen button in the settings window will cause the splash screens to be replayed, which could get annoying.

**Comment by Aami** [comment]
Well, I don't know if I fixed it without knowing it, but, it brings me back to the menu buttons for me.

**Comment by acidpoison** [comment]
I'll check it in the new version. It could just be a personal issue with my computer. I hope not.

**Comment by acidpoison** [comment]
Nope, the game still replays the splash screens when you select back to title in the options screen.

**Comment by Aami** [comment]
Mmmmh... I'm going to fix this!

**Comment by Aami** [comment]
Oh, well, I actually can't change this, because it's incorporated in the software too, it comes back to the page and not to the label.
